name=TinyRTOS
version=1.2.0
author=Nikolai Radke
maintainer=Nikolai Radke
sentence=Cooperative task scheduler with resource locks for ATtiny and ATmega AVR MCUs.
paragraph=Enables cooperative multitasking on AVR MCUs with as little as 256 bytes of RAM. Compatible with any AVR MCU (like ATtiny45 oder ATmega328) with up to 128 KB flash. Experimental ATmega2560 support. 
included.url= https://github.com/NikolaiRadke/TinyRTOS
architectures=avr
depends=
license=Apache-2.0
