name=TinyRTOS
version=1.0.0
author=Nikolai Radke
maintainer=Nikolai Radke
sentence=Cooperative task scheduler for ATtiny44/45/84/85.
paragraph=Enables cooperative multitasking on common ATtiny MCUs with as little as 256 bytes of RAM.
category=Timing
url= https://github.com/NikolaiRadke/TinyRTOS
architectures=avr
depends=
license=Apache-2.0
