name=TinyRTOS
version=1.1.0
author=Nikolai Radke
maintainer=Nikolai Radke
sentence=Cooperative task scheduler with resource locks for ATtiny and ATmega AVR MCUs.
paragraph=Enables cooperative multitasking on AVR MCUs with as little as 256 bytes of RAM. Supports classic ATtiny, tinyAVR 0/1/2-series and ATmega.
category=Timing
url= https://github.com/NikolaiRadke/TinyRTOS
architectures=avr
depends=
license=Apache-2.0
