name: Arduino CI

on:
  push:
  pull_request:

jobs:
  check-library:
    name: Check Arduino Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict

  check-examples:
    name: Compile Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v2
      - name: Install ATTinyCore
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://drazzy.com/package_drazzy.com_index.json
          arduino-cli core update-index
          arduino-cli core install ATTinyCore:avr --skip-post-install
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "ATTinyCore:avr:attinyx5:chip=85,clock=8internal,millis=enabled,LTO=Os"
          sketch-paths: |
            - examples
