name: Arduino CI

on:
  push:
  pull_request:

jobs:
  check-library:
    name: Check Arduino Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict

  check-examples:
    name: Compile Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v2
      - name: Install ATTinyCore from GitHub
        run: |
          arduino-cli config init
          mkdir -p $HOME/Arduino/hardware
          git clone --depth 1 https://github.com/SpenceKonde/ATTinyCore.git $HOME/Arduino/hardware/ATTinyCore
          mv $HOME/Arduino/hardware/ATTinyCore/avr $HOME/Arduino/hardware/ATTinyCore_avr
          rm -rf $HOME/Arduino/hardware/ATTinyCore
          mkdir -p $HOME/Arduino/hardware/ATTinyCore
          mv $HOME/Arduino/hardware/ATTinyCore_avr $HOME/Arduino/hardware/ATTinyCore/avr
          arduino-cli core update-index
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "ATTinyCore:avr:attinyx5:chip=85,clock=8internal,millis=enabled,LTO=Os"
          sketch-paths: |
            - examples
